[package]
name = "flate3"
version = "1.2.3"
authors = ["George Barwood"]
categories = ["compression"]
edition = "2021"
description = "High-performance RFC 1952 compression and de-compression"
license = "MIT OR Apache-2.0"
repository = "https://github.com/georgebarwood/flate3/"

[dependencies]
bchan = "1.0.0"
pstd = "1.0.134"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
lz4_flex = "0.11"
zstd = "0.13"
flate2 = "1"
miniz_oxide = "0.8"

[[bench]]
name = "compress"
harness = false
