[package]
name = "flate3"
version = "1.2.2"
authors = ["George Barwood"]
categories = ["compression"]
edition = "2021"
description = "High-performance RFC 1952 compression and de-compression"
license = "MIT OR Apache-2.0"
repository = "https://github.com/georgebarwood/flate3/"

[dependencies]
bchan = "1.0.0"
pstd = "1.0.134"
